# Generated by Django 4.2 on 2024-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='booking_number',
            field=models.CharField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
