# Generated by Django 4.2 on 2024-02-15 16:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_booking_original_basket_booking_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
