# Generated by Django 4.2 on 2024-02-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='time',
        ),
        migrations.AddField(
            model_name='lessons',
            name='class_size',
            field=models.SmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='lessons',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='max_age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='min_age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4.75, max_digits=4),
        ),
    ]
