# Generated by Django 4.2 on 2024-02-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lessons_day_remove_lessons_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
