# Generated by Django 4.2 on 2024-02-06 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_lessons_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Saturday', max_length=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.CharField(choices=[('9:00am', '9:00am'), ('10:00am', '10:00am'), ('11:00am', '11:00am'), ('12:00pm', '12:00pm'), ('1:00pm', '1:00pm'), ('2:00pm', '2:00pm'), ('3:00pm', '3:00pm')], default='12:00pm', max_length=15),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_size',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default='x', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='max_age',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='min_age',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='name', max_length=254),
            preserve_default=False,
        ),
    ]
